<a href="https://colab.research.google.com/github/tata-lakshman/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy


In [ ]:
import numpy as np #alias->np
a=5
a

5

Memory


In [ ]:

a=[1,2,3,4]

arr=np.array(a)

print("Array size:",arr.nbytes)

Array size: 32


In [ ]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
print(arr)

[1 2 3 4]


In [ ]:
print(arr.ndim)

1


If you no mention in the square brackete it will give 0 dimensions

In [ ]:
arr=np.array(32)
arr.ndim

0

In [ ]:
a=np.array([[]])
a.ndim

2

In [ ]:
a=np.array([[[]]])
a.shape

(1, 1, 0)

range


In [ ]:
range=np.arange(0,10)
range


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
range=np.arange(1,10,2) #Start,Stop,Step(By default the step value is 1)
range

array([1, 3, 5, 7, 9])

**linspace**

In [ ]:
arr=np.linspace(0,1,10) #Start,Stop,Number of values
arr

array([3.        , 3.33333333, 3.66666667, 4.        , 4.33333333,
       4.66666667, 5.        , 5.33333333, 5.66666667, 6.        ])

**logspace**

In [ ]:
arr=np.logspace(1,2,2)#Start,ending->powers
arr

array([ 10., 100.])

In [ ]:
#np.zeros->array full of Zeros
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

The another use of Numpy arrays is used to create Matrix[->Rows ^ Colums]

In [ ]:
arr=np.zeros([2,2])
arr

array([[0., 0.],
       [0., 0.]])

In [ ]:
#np.ones ->Array full of Ones
arr=np.ones(5,dtype=int) #By default it gives in float values
arr

array([1, 1, 1, 1, 1])

In [ ]:
arr=np.ones([2,3])
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#np.full->Creates a array full of Anyvalue
arr=np.full(10,2) #range,value
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
arr=np.full([2,3],7) #[row,colum],default value
arr

array([[7, 7, 7],
       [7, 7, 7]])

np.empty->It is used to override the values.It is Fast

In [ ]:
#np.empty Uninitialized array-> Create an array with out setting any value
arr=np.empty([2,2],dtype=int)
arr

array([[0, 0],
       [0, 0]])

In [ ]:
#random.rand
arr=np.random.rand(10) # Provide dimensions as separate integers
arr #random floats(0to1)

array([0.27162102, 0.42124776, 0.22834273, 0.47043222, 0.44330257,
       0.84900481, 0.7927377 , 0.39145161, 0.51915173, 0.20077304])

In [ ]:
arr=np.random.rand(2,3)#It is not taking any default value and no third parimeter we are not going to use Square brackets
arr

array([[0.75944416, 0.2954916 , 0.18184174],
       [0.24568376, 0.05387572, 0.84185444]])

In [ ]:
#ramdom.randn
arr=np.random.randn(10)#random floating numbers from normal distribution
print(arr)

[ 0.9126997   0.01501362  0.1372822   0.08385238  0.37113186  0.23080109
  1.13173253  2.27866229 -0.6268733  -0.14507752]


In [ ]:
arr=np.random.randn(2,4)
print(arr)

[[-0.3425663  -0.78390448 -1.19182129 -0.6469644 ]
 [-0.41747966 -0.02041731  1.57155946  0.0297666 ]]


In [ ]:
#random.randint
arr=np.random.randint(10)
print(arr)

6


In [ ]:
arr=np.random.randint(1,5)
print(arr)

2


In [ ]:
arr=np.random.randint(1,5,10)#Gives 10 values which ranges from 1 to 10.
print(arr)

[3 3 1 4 4 1 4 1 1 1]


In [ ]:
arr=np.random.randint(1,5,size=[2,3])#Start,Stop,dimension/number of values.
print(arr)

[[4 2 4]
 [4 1 2]]


In [ ]:
arr=np.random.randint(1,5,size=[2,3,2])#Start,Stop,dimension/number of values.
print(arr) #2 matrix,3 rows,2 colums.

[[[1 4]
  [1 1]
  [4 1]]

 [[3 4]
  [4 1]
  [1 1]]]


In [ ]:
arr=np.random.randint(1,5,size=[2,3,2,2])#Start,Stop,dimension/number of values.
print(arr)

[[[[1 3]
   [4 2]]

  [[1 1]
   [1 3]]

  [[2 1]
   [1 1]]]


 [[[3 2]
   [3 4]]

  [[4 4]
   [3 2]]

  [[2 3]
   [2 2]]]]


In [ ]:
arr=np.random.randint(1,5,size=[2,3,2,2,2])#Start,Stop,dimension/number of values.
print(arr) #2 matrix,3 rows,2 colums.

[[[[[4 4]
    [4 2]]

   [[2 4]
    [2 1]]]


  [[[2 4]
    [2 2]]

   [[2 2]
    [3 1]]]


  [[[1 3]
    [3 4]]

   [[4 3]
    [4 1]]]]



 [[[[2 1]
    [1 3]]

   [[3 4]
    [4 3]]]


  [[[2 1]
    [2 3]]

   [[4 1]
    [3 2]]]


  [[[3 4]
    [2 1]]

   [[2 2]
    [1 1]]]]]


Numpy Datatypes or type casting

In [ ]:
arr=np.array([1,2,3,4])
print(arr.dtype)

int64


In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
lst=['sai',1,2,4.5] #In numpy in list datatype the data should be in one datatype only
arr=np.array(lst) #So every thing is converted into string type.
arr

array(['sai', '1', '2', '4.5'], dtype='<U32')

Data Type   Description
int32       32-bit integer
int64       64-bit integer(default)
float32     32-bit float
float64     64-bit float(default)
bool        Boolean(True/false)
complex     complex numbers
str         unicode string

In [ ]:
arr=np.array([1,2,3,4,5])#By default it is int64
arr.dtype

dtype('int64')

In [ ]:
arr=np.array([1,2,3,4,5.6])
arr.dtype

dtype('float64')

In [ ]:
arr=np.array([1,2,3,4,5.6],dtype=int)
arr.dtype

dtype('int64')

In [ ]:
arr=np.array([1,2,3,'4'])
arr.dtype

dtype('<U21')

In [ ]:
arr=np.array([1,2,3,'4'],dtype=int)
arr.dtype

dtype('int64')

In [ ]:
print(arr)

[1 2 3 4]


In [ ]:
arr=np.array([1,2,3,4],dtype=np.float64)
arr.dtype

dtype('float64')

#Type Casting->astype()
=>When we want to convert one data type into another we will use type casting.
=>This is going to create a New array with the values.Converted to other data type.It is not going to change the original array.

In [ ]:
arr=np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [ ]:
print(arr)

[1 2 3 4]


In [ ]:
new_arr=arr.astype(np.float64)
new_arr.dtype

dtype('float64')

In [ ]:
print(new_arr)

[1. 2. 3. 4.]


In [ ]:
new_arr2=new_arr.astype(np.int64)
new_arr2

array([1, 2, 3, 4])

In [ ]:
#Type Casting Errors:
arr=np.array(['1','2','ram'])
arr2=arr.astype(np.int64)
print(arr2)

ValueError: invalid literal for int() with base 10: np.str_('ram')

In [ ]:
arr=np.array([[1,3,5],
              [7,8,9]])
print(arr)

[[1 3 5]
 [7 8 9]]


In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(2, 3)

In [ ]:
arr.size

6

In [ ]:
arr.itemsize

8

#Array Reshaping->reshape,ravel,flatten.
=>Some times we can change the shape of array without changing the data.

In [ ]:
#reshape
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [ ]:
reshape=arr.reshape(2,3)#2*3=6
print(reshape)

[[1 2 3]
 [4 5 6]]


In [ ]:
reshape=arr.reshape(3,1)#3*1=3
print(reshape)

ValueError: cannot reshape array of size 6 into shape (3,1)

In [ ]:
reshape2=arr.reshape(3,2)#3*2=6
print(reshape2)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#ravel->Convert 1D array
ravel=reshape2.ravel()
print(ravel)

[1 2 3 4 5 6]


In [ ]:
ravel[0]=100
print(ravel)
print(reshape2)

[100   2   3   4   5   6]
[[100   2]
 [  3   4]
 [  5   6]]


In [ ]:
#flatten->Convert to 1D array
flat=reshape2.flatten()
print(flat)

[100   2   3   4   5   6]


In [ ]:
print(reshape2)

[[100   2]
 [  3   4]
 [  5   6]]


#Difference between ravel and flatten
=>Both the functions are same.Both the function convert to 1D array
=>But when ever we are using the ravel method we are basically returning the view of the original array.When ever we make changes they are directly reflecting in the original array.
=>But when ever we use flatten there is zero connection's with the original array.

In [ ]:
flat[0]=1
print(flat)
print(reshape2)

[1 2 3 4 5 6]
[[100   2]
 [  3   4]
 [  5   6]]


#Arithmetic Operators or Arrays


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
#addition
print(a+b)

[5 7 9]


In [ ]:
#subtraction
print(b-a)

[3 3 3]


In [ ]:
#division
print(a/b)

[0.25 0.4  0.5 ]


In [ ]:
print((b/a).astype(int))

[4 2 2]


In [ ]:
#modulus ->Reminder
print(b%a)

[0 1 0]


In [ ]:
#exponent =>Power
print(a**b)

[  1  32 729]


In [ ]:
print(a**2)

[1 4 9]


In [ ]:
import numpy as np


#Universal functions=>vfuncs

In [ ]:
arr=np.array([1,4,9,16])
#np.sqrt(arr)#square root
print(np.sqrt(arr).astype(int))

[1 2 3 4]


In [ ]:
#Exponention
print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [ ]:
#sine function=>np.sin
angles=np.array([0,np.pi/2,np.pi])
print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


#Indexing and Slicing
  -5-4-3-2-1
a=[1,2,3,4,5]
   0 1 2 3 4
   a[0]=1 or a[-5]=1
#In python it supports -ve index as well.
  Start
    !
a[0:3]
  !
 end(It will never include)
 a[-1:-4:-1]=>In -ve index we should mention the step value.

In [ ]:
a=[1,2,3,4,5]
a[-1:-4]

[]

In [ ]:
a[-1:-4:-1]

[5, 4, 3]

In [ ]:
a[::2]

[1, 3, 5]

In [ ]:
#Negative Indexing
print(a[-1])

5


In [ ]:
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(np.ndenumerate(matrix))

In [ ]:
print(matrix[1:2,2:3])

[[6]]


In [ ]:
print(matrix[0:2,:])

[[1 2 3]
 [4 5 6]]


In [ ]:
print(matrix[:,:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(matrix[1:,1:])

[[5 6]
 [8 9]]


In [ ]:
#np.take Built in function to perform indexing and slicing.
arr=np.array([10,20,30,40,50])
ind=[1,2]
print(np.take(arr,ind))

[20 30]


In [ ]:
#Iteration with nditer()=>loop
arr=np.array([[1,2],
              [3,4]])
for x in np.nditer(arr):
  print(x,end=' ')

1 2 3 4 

In [ ]:
#ndenumerate()=>It will print both index+value
for ind,x in np.ndenumerate(arr):
  print(ind,x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [ ]:
for ind,x in np.ndenumerate(matrix):
  print(ind,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9


#views vs copy
#views =>The original array is going to be effected.
#copy =>The original array is unchanged.

In [ ]:
arr=np.array([1,2,3,4,5])
view=arr[1:3]
print(view)

[2 3]


In [ ]:
view[1]=200

In [ ]:
view

array([  2, 200])

## NumPy Views vs. Copies

When working with NumPy arrays, it's important to understand the distinction between a **view** and a **copy**.

*   **View**: A view is a *reference* to the original array's data. It's like looking at the same data through a different window (with potentially a different shape or selection of elements). **Changes made to a view will directly affect the original array.** This is because both the view and the original array share the same underlying data buffer in memory.

*   **Copy**: A copy is a *new* array that contains a complete duplicate of the original array's data. It has its own independent memory location. **Changes made to a copy will NOT affect the original array.**

In your notebook, the code demonstrates this:

*   `view = arr[1:3]` creates a **view**. When you modify `view[1]`, the corresponding element in the original `arr` is also changed.
*   `copy = arr[1:3].copy()` creates a **copy**. When you modify `copy[1]`, the original `arr` remains unchanged.

Understanding this difference is crucial for avoiding unexpected behavior when manipulating NumPy arrays.

In [ ]:
print(arr)

[  1 200 200   4   5]


In [ ]:
#copy
copy=arr[1:3].copy()
print(copy)

[200 200]


In [ ]:
copy[1]=2
copy

array([200,   2])

In [ ]:
copy[0]=100
copy

array([100,   2])

In [ ]:
print(arr)

[  1 200 200   4   5]


In [ ]:
#Transpose=>Interchanging of row and colum
arr=np.array([[1,2],
              [3,4]])
print(arr)

[[1 2]
 [3 4]]


In [ ]:
print(np.transpose(arr))

[[1 3]
 [2 4]]


In [ ]:
#swapaxes=>swap 2 specific axes in a matrix.
arr=np.array([[[1,2],
               [3,4],
               [5,6],
               [7,8]]])
print(arr.shape)

(1, 4, 2)


In [ ]:
print(arr.size)

8


In [ ]:
swap=np.swapaxes(arr,0,2)
print(swap)

[[[1]
  [3]
  [5]
  [7]]

 [[2]
  [4]
  [6]
  [8]]]


In [ ]:
print(swap.shape)

(2, 4, 1)


In [ ]:
swap=np.swapaxes(arr,0,1)
print(swap.shape)

(4, 1, 2)


In [ ]:
swap1=np.swapaxes(arr, 0, 1) # Assuming you meant to swap axes 0 and 1 as in the previous example
print(swap1)

[[[1 2]]

 [[3 4]]

 [[5 6]]

 [[7 8]]]


#concenation
a=[1,2]
b=[3,4]
if it is (a+b) wrong

In [ ]:
#Concenation
a=np.array([1,2,3])
b=np.array([4,5,6])
combine=np.concatenate((a,b))
print(combine)

[1 2 3 4 5 6]


#vertical Stack(vstack)

In [ ]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(np.array([arr1,arr2]))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
print(np.vstack((arr1,arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


#horizontal Stack(hstack)

In [ ]:
#np.hstack
print(np.hstack((arr1,arr2)))

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
print(np.stack((arr1,arr2),axis=0))#axis=0(rows)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
print(np.stack((arr1,arr2),axis=1))#axis=1(colums)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [ ]:
print(np.stack((arr1,arr2),axis=2))#axis=2(depth)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [ ]:
#splitting arrays
arr1=np.array([[1,2],[3,4],[5,6],[7,8]])
arr1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
print(np.split(arr1,2))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [ ]:
print(np.split(arr1,2,axis=1))

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


In [ ]:
print(np.split(arr1,2,axis=0))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [ ]:
print(np.array_split(arr1,3))

[array([[1, 2],
       [3, 4]]), array([[5, 6]]), array([[7, 8]])]


In [ ]:
print(np.array_split(arr1,3,axis=1))

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([], shape=(4, 0), dtype=int64)]


In [ ]:
print(np.array_split(arr1,3,axis=0))

[array([[1, 2],
       [3, 4]]), array([[5, 6]]), array([[7, 8]])]


In [ ]:
print(np.array_split(arr1,4))#the axis parameter is not specified and defaults to 0.

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]


In [ ]:
print(np.split(arr1,4))

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]


In [ ]:
try:
  print(np.split(arr1, 3))
except ValueError as e:
  print(f"Error: {e}")

Error: array split does not result in an equal division


In [ ]:
print(np.nsplit(arr1,2))  # it not recognized in pandas

AttributeError: module 'numpy' has no attribute 'nsplit'

In [ ]:
#Repeating
arr=np.array([1,2,3])
print(np.repeat(arr,2))

[1 1 2 2 3 3]


In [ ]:
print(np.repeat(arr,3))

[1 1 1 2 2 2 3 3 3]


In [ ]:
#Tile =>It will repeat my whole array
print(np.tile(arr,2))


[1 2 3 1 2 3]


In [ ]:
#Aggregate Functions(method) #In programming, a method is a function that "belongs" to an object or a class. It's a block of code that performs a specific action and is associated with a particular type of data (the object it belongs to).
arr=np.array([1,2,3])
print(np.sum(arr))

6


In [ ]:
print(np.min(arr))

1


In [ ]:
print(np.max(arr))

3


In [ ]:
print(np.mean(arr)) #It gives the value in float

2.0


In [ ]:
print(np.median(arr))

2.0


In [ ]:
np.std(arr)

np.float64(0.816496580927726)

In [ ]:
np.var(arr)

np.float64(0.6666666666666666)

In [ ]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(np.sum(matrix))

45


In [ ]:
print(np.sum(matrix,axis=0))#column wise

[12 15 18]


In [ ]:
print(np.sum(matrix,axis=1))#row wise

[ 6 15 24]


In [ ]:
#cumulative operations =>running total
arr=np.array([1,2,3])
print(np.cumsum(arr))

[1 3 6]


In [ ]:
print(np.cumprod(arr))

[1 2 6]


#conditional based choices

In [ ]:
#where
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
result=np.where(arr<2,"Low","High")#numpy.where(condition, x, y)
print(result)

['Low' 'High' 'High']


In [ ]:
#argwhere
arr=np.array([10,25,35,50])
print(arr)

[10 25 35 50]


In [ ]:
print(np.argwhere(arr>20))#numpy.argwhere(condition) It will give the index value.

[[1]
 [2]
 [3]]


In [ ]:
#logical_and
mask=np.logical_and(arr>15,arr<50)
print(mask)

[False  True  True False]


In [ ]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(np.argwhere(matrix>5))

[[1 2]
 [2 0]
 [2 1]
 [2 2]]


In [ ]:
print(arr[mask])#The values which are true will be given.

[25 35]


In [ ]:
#logical_or
arr3=np.array([1,2,3,4,5])
mask2=np.logical_or(arr3<1,arr3<3)
print(mask2)


[ True  True False False False]


In [ ]:
print(arr3[mask2])

[1 2]


In [ ]:
arr2=np.array([1,0,5,9,0,7])
print(arr2)

[1 0 5 9 0 7]


In [ ]:
print(np.nonzero(arr2))#It will print the index value of the elements which are non-zero.

(array([0, 2, 3, 5]),)


#Broad Casting
Broad casting is automatically stretch the smaller array to match the shape of the bigger array.
Rules(very important):Numpy compares the shape of the array from the end(right to left)
1)If shapes are equal,they are compatible.
2)If 1 is 1,it can be stretched to match the other.
3)If shapes are different and not 1 or equal then ERROR

Broadcasting is a powerful feature in NumPy that allows you to perform operations on arrays of different shapes. When NumPy performs an operation (like addition, subtraction, multiplication, etc.) on two arrays, it checks if they are compatible according to a set of rules. If they are, NumPy will "stretch" or "broadcast" the smaller array to match the shape of the larger array so the operation can be performed element-wise. This avoids the need to explicitly create larger temporary arrays, which can save memory and improve performance.

Here are the rules NumPy follows when comparing the shapes of two arrays, starting from the trailing (rightmost) dimension:

Equal dimensions: If the dimensions are the same size, they are compatible.
One dimension is 1: If one of the dimensions is 1, it can be stretched (broadcast) to match the size of the other dimension.
Dimensions are different and neither is 1: If the dimensions are different and neither is 1, the arrays are incompatible, and a ValueError will be raised.

In [ ]:
#Broad Casting
image=np.array([[200,150],[100,250]])
print(image)

[[200 150]
 [100 250]]


In [ ]:
brightness=image+50
print(brightness)

[[250 200]
 [150 300]]


In [ ]:
print(image.shape)

(2, 2)


#vectorization
#The np.vectorize() function is used to create a vectorized function from a regular Python function. This can be helpful for applying a function that is not already vectorized by NumPy to elements of a NumPy array. It's important to note that np.vectorize() is primarily for convenience and does not necessarily improve performance compared to a carefully implemented NumPy vectorized operation.

In [ ]:
#np.vectorize()->Convert a regular function to be applied on an array.
def sqrt(x):
  return x*x
vfunc=np.vectorize(sqrt)
arr=np.array([1,2,3])
print(vfunc(arr))

[1 4 9]


#vectorized(pros)
1)when you want to apply a custom function to every element.
2)for readability
#Cons
1)It's not faster than a loop.
2)It only makes syntax cleaner,but does not improve improve speed like real vectorized Numpy function.